# Generated by Django 2.2.6 on 2019-11-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20191113_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('category',), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
