# Generated by Django 2.2.6 on 2019-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20191113_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_cook',
            field=models.BooleanField(default=False, verbose_name='es cocinero ?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_waiter',
            field=models.BooleanField(default=False, verbose_name='es mozo ?'),
        ),
    ]
