# Generated by Django 2.2.6 on 2019-11-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20191116_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
