# Generated by Django 2.2.6 on 2019-10-31 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField(default=0)),
                ('family', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='items.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            options={
                'verbose_name': '5. Postre',
                'verbose_name_plural': '5. Postres',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            options={
                'verbose_name': '6. Bebida',
                'verbose_name_plural': '6. Bebidas',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            options={
                'verbose_name': '3. Entrada',
                'verbose_name_plural': '3. Entradas',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='HotDrink',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            options={
                'verbose_name': '7. Bebida Caliente',
                'verbose_name_plural': '7. Bebidas Calientes',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            options={
                'verbose_name': '4. Plato Principal',
                'verbose_name_plural': '4. Platos Principales',
            },
            bases=('items.item',),
        ),
    ]
