# Generated by Django 2.2.6 on 2019-11-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes_cook',
            field=models.TextField(blank=True, verbose_name='notas cocinero'),
        ),
        migrations.AddField(
            model_name='item',
            name='notes_waiter',
            field=models.TextField(blank=True, verbose_name='notas mozo'),
        ),
    ]
