# Generated by Django 2.2.6 on 2019-10-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_dessert_drink_entry_hotdrink_item_maincourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'verbose_name': '4. Postre', 'verbose_name_plural': '4. Postres'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': '5. Bebida', 'verbose_name_plural': '5. Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '2. Entrada', 'verbose_name_plural': '2. Entradas'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': '1. Familia', 'verbose_name_plural': '1. Familias'},
        ),
        migrations.AlterModelOptions(
            name='hotdrink',
            options={'verbose_name': '6. Bebida Caliente', 'verbose_name_plural': '6. Bebidas Calientes'},
        ),
        migrations.AlterModelOptions(
            name='maincourse',
            options={'verbose_name': '3. Plato Principal', 'verbose_name_plural': '3. Platos Principales'},
        ),
    ]
