# Generated by Django 2.2.6 on 2019-11-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191031_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('family',)},
        ),
    ]
