# Generated by Django 2.2.6 on 2019-11-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191107_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ('name',), 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AddField(
            model_name='family',
            name='idx',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
    ]
