# Generated by Django 2.2.6 on 2019-11-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0045_auto_20191104_2336'),
        ('items', '0004_auto_20191104_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='hotdrink',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='maincourse',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='HotDrink',
        ),
        migrations.DeleteModel(
            name='MainCourse',
        ),
    ]
