# Generated by Django 2.2.6 on 2019-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20191108_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='descripción'),
        ),
    ]
