# Generated by Django 2.2.6 on 2019-11-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20191104_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
    ]
