# Generated by Django 2.2.6 on 2019-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191108_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
