# Generated by Django 2.2.6 on 2019-11-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191105_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('family',), 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre'),
        ),
    ]
