# Generated by Django 2.2.6 on 2019-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20191111_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dam0dmleq/image/upload/v1573501278/pcm/empty_black.png', max_length=200, verbose_name='imagen'),
        ),
    ]
