# Generated by Django 2.2.6 on 2019-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20191116_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('family', 'name'), 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
