# Generated by Django 2.2.6 on 2019-11-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20191116_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='items.Family', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio'),
        ),
    ]
