# Generated by Django 2.2.6 on 2019-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20191116_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
