# Generated by Django 2.2.6 on 2019-11-07 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('family', models.CharField(blank=True, max_length=200)),
                ('family_id', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, to='items.Item')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
