# Generated by Django 2.2.6 on 2019-11-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='family_id',
        ),
    ]
