# Generated by Django 2.2.6 on 2019-10-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.AddField(
            model_name='item',
            name='menus',
            field=models.ManyToManyField(to='menus.Menu'),
        ),
    ]
