# Generated by Django 2.2.6 on 2019-10-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20191029_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='item_0',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='menus.Item'),
        ),
    ]
