# Generated by Django 2.2.6 on 2019-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20191030_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='main_courses',
            field=models.ManyToManyField(to='menus.MainCourse'),
        ),
    ]
