# Generated by Django 2.2.6 on 2019-10-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_menu_main_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='name',
            field=models.CharField(default='x', max_length=10),
        ),
        migrations.AddField(
            model_name='family',
            name='title',
            field=models.CharField(default='x', max_length=20),
        ),
        #migrations.AddField(
        #    model_name='item',
        #    name='family',
            #field=models.ForeignKey(default='x', on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
            #field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
        #    field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
        #),
    ]
