# Generated by Django 2.2.6 on 2019-10-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_auto_20191030_1756'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='item',
    #        name='family',
    #        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
    #    ),
    #]
