# Generated by Django 2.2.6 on 2019-10-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20191030_1757'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='item',
    #        name='family',
    #    ),
    #]
