# Generated by Django 2.2.6 on 2019-10-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_item_family'),
    ]

    #operations = [
    #    migrations.AddField(
    #        model_name='item',
    #        name='family',
    #        field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
    #    ),
    #]
