# Generated by Django 2.2.6 on 2019-10-30 18:28

from django.db import migrations, models
import django.db.models.deletion
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_item_family'),
    ]

    #operations = [
    #    migrations.AddField(
    #        model_name='item',
    #        name='family',
    #        field=models.ForeignKey(default=menus.models.Item.get_family, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
    #    ),
    #]
