# Generated by Django 2.2.6 on 2019-10-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_auto_20191030_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
