# Generated by Django 2.2.6 on 2019-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
