# Generated by Django 2.2.6 on 2019-10-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0017_auto_20191030_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Item')),
            ],
            bases=('menus.item',),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Item')),
            ],
            bases=('menus.item',),
        ),
    ]
