# Generated by Django 2.2.6 on 2019-10-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_dessert_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desserts',
            field=models.ManyToManyField(to='menus.Dessert'),
        ),
        migrations.AddField(
            model_name='menu',
            name='entries',
            field=models.ManyToManyField(to='menus.Entry'),
        ),
    ]
