# Generated by Django 2.2.6 on 2019-10-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0019_auto_20191030_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
    ]
