# Generated by Django 2.2.6 on 2019-10-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0020_auto_20191030_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Item')),
            ],
            bases=('menus.item',),
        ),
        migrations.CreateModel(
            name='HotDrinks',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Item')),
            ],
            bases=('menus.item',),
        ),
        migrations.AddField(
            model_name='menu',
            name='driks',
            field=models.ManyToManyField(to='menus.Drinks'),
        ),
        migrations.AddField(
            model_name='menu',
            name='hot_drinks',
            field=models.ManyToManyField(to='menus.HotDrinks'),
        ),
    ]
