# Generated by Django 2.2.6 on 2019-10-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0021_auto_20191030_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='driks',
            new_name='drinks',
        ),
    ]
