# Generated by Django 2.2.6 on 2019-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_auto_20191030_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='desserts',
            field=models.ManyToManyField(blank=True, to='menus.Dessert'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='entries',
            field=models.ManyToManyField(blank=True, to='menus.Entry'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='main_courses',
            field=models.ManyToManyField(blank=True, to='menus.MainCourse'),
        ),
    ]
