# Generated by Django 2.2.6 on 2019-10-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0025_auto_20191030_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
        ),
    ]
