# Generated by Django 2.2.6 on 2019-10-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0027_auto_20191030_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_title',
            new_name='title',
        ),
    ]
