# Generated by Django 2.2.6 on 2019-10-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0028_auto_20191030_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
