# Generated by Django 2.2.6 on 2019-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0029_auto_20191030_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
    ]
