# Generated by Django 2.2.6 on 2019-10-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0030_auto_20191030_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'verbose_name': '5. Postre', 'verbose_name_plural': '5. Postres'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': '6. Bebida', 'verbose_name_plural': '6. Bebidas'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '3. Entrada', 'verbose_name_plural': '3. Entradas'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': '2. Familia', 'verbose_name_plural': '2. Familias'},
        ),
        migrations.AlterModelOptions(
            name='hotdrink',
            options={'verbose_name': '7. Bebida Caliente', 'verbose_name_plural': '7. Bebidas Calientes'},
        ),
        migrations.AlterModelOptions(
            name='maincourse',
            options={'verbose_name': '4. Plato Principal', 'verbose_name_plural': '4. Platos Principales'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '1. Menu', 'verbose_name_plural': '1. Menus'},
        ),
    ]
