# Generated by Django 2.2.6 on 2019-10-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0032_auto_20191030_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, choices=[('entry', 'Entrada'), ('main_course', 'Plato Principal'), ('dessert', 'Postre'), ('drink', 'Bebida'), ('hot_drink', 'Bebida Caliente')], max_length=100),
        ),
    ]
