# Generated by Django 2.2.6 on 2019-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0033_auto_20191030_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
