# Generated by Django 2.2.6 on 2019-10-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0034_auto_20191030_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='title',
        ),
    ]
