# Generated by Django 2.2.6 on 2019-10-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0037_auto_20191031_1615'),
    ]

    operations = [
        #migrations.CreateModel(
        #    name='Family',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('name', models.CharField(blank=True, max_length=100)),
        #    ],
        #    options={
        #        'verbose_name': '2. Familia',
        #        'verbose_name_plural': '2. Familias',
        #    },
        #),
        #migrations.AlterField(
        #    model_name='item',
        #    name='family',
        #    field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='menus.Family'),
        #),
    ]
