# Generated by Django 2.2.6 on 2019-10-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0039_auto_20191031_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='hotdrink',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='family',
        ),
        migrations.RemoveField(
            model_name='maincourse',
            name='item_ptr',
        ),
        migrations.AlterField(
            model_name='menu',
            name='desserts',
            field=models.ManyToManyField(blank=True, to='items.Dessert'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='items.Drink'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='entries',
            field=models.ManyToManyField(blank=True, to='items.Entry'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='hot_drinks',
            field=models.ManyToManyField(blank=True, to='items.HotDrink'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='main_courses',
            field=models.ManyToManyField(blank=True, to='items.MainCourse'),
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='HotDrink',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='MainCourse',
        ),
    ]
