# Generated by Django 2.2.6 on 2019-10-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191031_2111'),
        ('menus', '0041_auto_20191031_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='items.Item'),
        ),
    ]
