# Generated by Django 2.2.6 on 2019-11-01 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0042_menu_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='fecha'),
        ),
    ]
