# Generated by Django 2.2.6 on 2019-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0043_auto_20191101_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='family',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='menu',
            name='family_id',
            field=models.IntegerField(default=0),
        ),
    ]
