# Generated by Django 2.2.6 on 2019-11-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0044_auto_20191104_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='desserts',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='hot_drinks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='main_courses',
        ),
    ]
