# Generated by Django 2.2.6 on 2019-11-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0045_auto_20191104_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='name',
        ),
    ]
