# Generated by Django 2.2.6 on 2019-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191105_1738'),
        ('menus', '0046_auto_20191105_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dishes',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.Item'),
        ),
    ]
