# Generated by Django 2.2.6 on 2019-11-07 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0047_auto_20191105_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 0, 24, 49, 150386), verbose_name='fecha'),
        ),
    ]
