# Generated by Django 2.2.6 on 2019-11-07 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0048_auto_20191107_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 19, 43, 7, 838255), verbose_name='fecha'),
        ),
    ]
