# Generated by Django 2.2.6 on 2019-11-07 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0049_auto_20191106_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 19, 46, 16, 308001), verbose_name='fecha'),
        ),
    ]
