# Generated by Django 2.2.6 on 2019-11-07 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0057_auto_20191106_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='family',
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 49, 37, 336485), verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.Item'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
