# Generated by Django 2.2.6 on 2019-11-07 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0061_auto_20191106_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 1, 52, 18, 172840, tzinfo=utc), verbose_name='fecha'),
        ),
    ]
