# Generated by Django 2.2.6 on 2019-11-13 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tables', '0001_initial'),
        ('items', '0009_auto_20191111_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('active', models.BooleanField(default=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cook', to='employees.Employee')),
                ('items', models.ManyToManyField(to='items.Item')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.Table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiter', to='employees.Employee')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('name',),
            },
        ),
    ]
