# Generated by Django 2.2.6 on 2019-11-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191113_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cook',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cook': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cook', to='employees.Employee'),
        ),
    ]
