# Generated by Django 2.2.6 on 2019-11-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cook',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cook': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cook', to='employees.Employee', verbose_name='cocinero'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.Table', verbose_name='mesa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(limit_choices_to={'is_waiter': True}, on_delete=django.db.models.deletion.PROTECT, related_name='waiter', to='employees.Employee', verbose_name='mozo'),
        ),
    ]
