# Generated by Django 2.2.6 on 2019-11-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191115_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',), 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item', verbose_name='plato'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
    ]
