# Generated by Django 2.2.6 on 2019-11-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191115_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cook',
        ),
    ]
