# Generated by Django 2.2.6 on 2019-11-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Inicio'), ('preparation', 'En preparacion'), ('served', 'Servido'), ('paid', 'Pagado'), ('cancel', 'Cancelado')], default='draft', max_length=100),
        ),
    ]
