# Generated by Django 2.2.6 on 2019-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191116_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('en preparacion', 'En preparacion'), ('servido', 'Servido'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='inicio', max_length=100),
        ),
    ]
