# Generated by Django 2.2.6 on 2019-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191116_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Preparación', 'En preparacion'), ('Servido', 'Servido'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Inicio', max_length=100),
        ),
    ]
