# Generated by Django 2.2.6 on 2019-11-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191116_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
    ]
