# Generated by Django 2.2.6 on 2019-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191116_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='total'),
        ),
    ]
