# Generated by Django 2.2.6 on 2019-11-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20191116_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='total',
        ),
    ]
