# Generated by Django 2.2.6 on 2019-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Preparación', 'En preparacion'), ('Listo', 'Listo'), ('Servido', 'Servido'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Inicio', max_length=100),
        ),
    ]
