# Generated by Django 2.2.6 on 2019-11-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderline_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('item',), 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
    ]
